keyword:
  - 'error:red'
  - 'warn:yellow'
  - 'info:green'
  - 'debug:blue'
color:
  black: "\e[30m"
  red: "\e[31m"
  green: "\e[32m"
  yellow: "\e[33m"
  blue: "\e[34m"
  magenta: "\e[35m"
  cyan: "\e[36m"
  gray: "\e[37m"
